name: flexible_horizontal_list_view
description: "A horizontal ListView that doesn't require a fixed height"
version: 0.1.1
repository: https://github.com/thanhle1547/flutter_horizontal_list_view
screenshots:
  - description: A horizontal scrollable list showing the use of the `.separated` constructor
    path: screenshots/seperated_constructor.gif
topics:
  - list-view
  - listview

environment:
  sdk: ^3.1.0
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
